chore: add precision value
MapColonies/3d-helm pull request #18
Opened 2023-11-29 13:46 UTC by heliprokupetz14

2023-11-29 15:24 UTC, netanelC requested changes
You should import the precision from the pycsw.cfg instead of setting a new env

2023-11-30 11:29 UTC, RonitKissis commented on charts/serving/charts/pycsw/values.yaml
> +  bboxPrecisionDigits: 5
why 5? if the user has provided only 3 digits after the dot? or he has given 8 and i want all of them?

2023-11-30 12:17 UTC, netanelC commented on charts/serving/charts/pycsw/values.yaml
> +  bboxPrecisionDigits: 5
the precision number can be bigger than the actial digits number. The function will act as she got the length number of the digits.
About the '5' value, agree

2023-12-03 15:48 UTC, RonitKissis approved these changes
whai whai

2023-12-03 15:51 UTC, merged