pycsw server
MapColonies/3d-helm pull request #21
Opened 2023-12-24 13:09 UTC by heliprokupetz14

2023-12-25 08:44 UTC, netanelC requested changes

2023-12-25 08:44 UTC, netanelC commented on charts/serving/charts/pycsw/templates/_helpers.tpl
> -
Remove this unnecessary change

2023-12-25 08:44 UTC, netanelC commented on charts/serving/charts/pycsw/templates/_helpers.tpl
> +  Set the PYCSW_SERVER_URL environment variable based on the route of pycsw.
Fix this description. It is written as a mission. You can see other functions in this file to see some good examples

2023-12-25 08:44 UTC, netanelC commented on charts/serving/charts/pycsw/templates/_helpers.tpl
> +  {{- with .Values.route -}}
Remove this "with" option. It makes the code less readable. It is better to write ".Values.route.VALUE"

2023-12-25 08:44 UTC, netanelC commented on charts/serving/charts/pycsw/templates/deployment.yaml
> +{{- $route := include "pycsw-setServerURL" . -}}
replace "route" var with a better name. Maybe "serverURL".

Same for "pycsw-setServerURL", try to keep the exist design ("pycsw." and not "pycsw-")

2023-12-25 08:44 UTC, netanelC commented on values-dev.yaml
> +      enabled: true
Why did you change it?

2023-12-25 08:44 UTC, netanelC commented on values-dev.yaml
> +      host: 10.0.0.4
Why did you change this line and the next lines? values should be with no changes

2023-12-25 08:49 UTC, heliprokupetz14 commented on charts/serving/charts/pycsw/templates/_helpers.tpl
> +  {{- with .Values.route -}}
the with is to use the values from the route...

2023-12-25 09:28 UTC, netanelC requested changes

2023-12-25 09:28 UTC, netanelC commented on charts/serving/charts/pycsw/templates/_helpers.tpl
> +{{- end -}}
Add an empty line to separate the functions

2023-12-25 09:28 UTC, netanelC commented on charts/serving/charts/pycsw/templates/_helpers.tpl
> +  {{- if .Values.route -}}
Always true. Why did you write this?

2023-12-25 09:28 UTC, netanelC commented on charts/serving/charts/pycsw/templates/_helpers.tpl
> +{{- define "pycsw.setServerURL" -}}
Use better name:
```suggestion
{{- define "pycsw.serverURL" -}}
```

2023-12-25 09:28 UTC, netanelC commented on charts/serving/charts/pycsw/templates/_helpers.tpl
> +      {{- $protocol := .Values.route.https | ternary "https" "http" }}
That is not a good practice for using ternary.

2023-12-25 09:28 UTC, netanelC commented on charts/serving/charts/pycsw/templates/_helpers.tpl
> +      {{- if .Values.route.path }}
Is this necessary? 
If path is empty, I don't care about putting him as well

2023-12-25 09:39 UTC, heliprokupetz14 commented on charts/serving/charts/pycsw/templates/_helpers.tpl
> +      {{- if .Values.route.path }}
yes it is necessary.

2023-12-25 11:23 UTC, netanelC requested changes
Remove values changes

2023-12-25 16:57 UTC, shimoncohen commented on charts/serving/charts/pycsw/templates/_helpers.tpl
> +{{- end -}}
@heliprokupetz14 Do not resolve anything opened on something you did, you let the person who left the comment review and decide if you finished.

2023-12-25 17:07 UTC, shimoncohen approved these changes

2023-12-25 18:20 UTC, netanelC commented on charts/serving/charts/pycsw/templates/_helpers.tpl
> +{{- end -}}
@heliprokupetz14 You didn't add an empty line.

2023-12-25 18:24 UTC, shimoncohen commented on charts/serving/charts/pycsw/templates/_helpers.tpl
> +{{- end -}}
This proves my point.

2023-12-26 09:27 UTC, netanelC approved these changes

2023-12-26 09:27 UTC, merged