refactor: create global values
MapColonies/3d-helm pull request #29
Opened 2024-02-04 15:03 UTC by heliprokupetz14

2024-02-04 17:17 UTC, netanelC requested changes
There are some envs that are not related to S3 directly, like cache or debug.
I merged the PR about the cache so it will be easier for you to know what envs should be global.

2024-02-05 07:48 UTC, heliprokupetz14 commented on values-dev.yaml
> -    resources:
mistake

2024-02-05 09:43 UTC, netanelC requested changes

2024-02-05 09:43 UTC, netanelC commented on values-dev.yaml
> +      enabled: true
Keep the default value as false

2024-02-05 09:43 UTC, netanelC commented on values-dev.yaml
> +      enabled: true
Keep the default value as false

2024-02-05 09:43 UTC, netanelC commented on values-dev.yaml
> +      sigsVersion: 4
Why there are two env for signature version?

2024-02-05 09:43 UTC, netanelC commented on values-dev.yaml
> +      debug: true
Does not related to s3

2024-02-05 09:43 UTC, netanelC commented on values-dev.yaml
> +      style: path
style and forcePathStyle are supposed to be same. See how you can combine them

2024-02-05 09:45 UTC, heliprokupetz14 commented on values-dev.yaml
> +      enabled: true
ok

2024-02-05 09:45 UTC, heliprokupetz14 commented on values-dev.yaml
> +      enabled: true
ok

2024-02-05 09:48 UTC, heliprokupetz14 commented on values-dev.yaml
> +      debug: true
ok

2024-02-05 09:49 UTC, heliprokupetz14 commented on values-dev.yaml
> +      sigsVersion: 4
removed

2024-02-05 10:07 UTC, heliprokupetz14 commented on values-dev.yaml
> +      style: path
they cannot be combinned. the stype option is used to specify the URL style for requests and the forcepathstype is enforces the use of path-style URLs.

2024-02-05 10:29 UTC, netanelC requested changes

2024-02-05 10:29 UTC, netanelC commented on values-dev.yaml
> +      style: path
Exactly. You can set the forcePathStyle env according to the style

2024-02-05 14:18 UTC, netanelC requested changes
In pycsw, there are more values related to postgres under authentication

2024-02-06 08:19 UTC, netanelC requested changes

2024-02-06 08:19 UTC, netanelC commented on charts/ingestion/templates/configmap.yaml
> +  S3_DEST_FORCE_PATH_STYLE: {{ if eq .Values.global.S3.destination.style "path" -}}
Consider using ternary

2024-02-06 08:51 UTC, heliprokupetz14 commented on charts/ingestion/templates/configmap.yaml
> +  S3_DEST_FORCE_PATH_STYLE: {{ if eq .Values.global.S3.destination.style "path" -}}
rafactored

2024-02-06 09:14 UTC, netanelC requested changes

2024-02-06 09:14 UTC, netanelC commented on charts/serving/charts/nginx-s3-gateway/templates/configmap.yaml
> +  {{- if eq .Values.global.S3.destination.sigVersion "v2" }}
You can just make the sigVersion as a number (for example: "2" instead of "v2") and concatenate the "v" before it in the configmap when it is necessary

2024-02-06 09:14 UTC, netanelC commented on charts/ingestion/templates/configmap.yaml
> +
Remove the change

2024-02-06 09:14 UTC, netanelC commented on values-dev.yaml
> +  # ====================================================================================================
There is already a block for global values at the beginning of the file, you can move the values in there

2024-02-06 09:51 UTC, heliprokupetz14 commented on charts/ingestion/templates/configmap.yaml
> +
removed

2024-02-06 09:52 UTC, heliprokupetz14 commented on values-dev.yaml
> +  # ====================================================================================================
moved

2024-02-06 10:02 UTC, heliprokupetz14 commented on charts/serving/charts/nginx-s3-gateway/templates/configmap.yaml
> +  {{- if eq .Values.global.S3.destination.sigVersion "v2" }}
fixed

2024-02-06 12:03 UTC, heliprokupetz14 commented on values-dev.yaml
> -        secretName: catalog-3d-dev-secret
fixed

2024-02-07 16:55 UTC, netanelC requested changes
Seems very good!
Two things:
1. In some cases you wrote user instead of SSL, check again the PR and make the changes in the right places (I didn't comment all of them, be a good head).
2. Every comment on pycsw, relevant for pycsw-all

2024-02-07 16:55 UTC, netanelC commented on charts/ingestion/charts/ingestion-catalog/templates/secret.yaml
> +{{- if not .Values.global.postgres.ssl.useExternal -}}
This is for creation user configs and not ssl

2024-02-07 16:55 UTC, netanelC commented on charts/ingestion/templates/configmap.yaml
> +  S3_DEST_SIG_VERSION: v{{ .Values.global.S3.destination.sigVersion }}
Does S3_SOURCE_SIG_VERSION env is different from S3_DEST_SIG_VERSION?
Why did you add the 'v' char only to destination?

2024-02-07 16:55 UTC, netanelC commented on charts/serving/charts/nginx-s3-gateway/templates/configmap.yaml
> +  AWS_SIGS_VERSION: {{ .Values.global.S3.destination.sigVersion | quote }}
Keep the quote at the first of the value, it is the convention in the whole file

2024-02-07 16:55 UTC, netanelC commented on values-dev.yaml
> +  # ====================================================================================================
Remove this comment. You are already in the global scope from the beginning of the file

2024-02-07 16:55 UTC, netanelC commented on values-dev.yaml
> +      secretName: 'catalog-3d-dev-secret'
Keep the useExternal, we want to know if we are using an external secret or creating a new one

2024-02-07 16:55 UTC, netanelC commented on values-dev.yaml
> +
Remove this

2024-02-07 16:55 UTC, netanelC commented on values-dev.yaml
> +      requirePassword: true
Keep the rejectUnauthorized from pycsw config

2024-02-07 16:55 UTC, netanelC commented on charts/serving/charts/pycsw-all/templates/_helpers.tpl
> +{{- if .Values.global.postgres.requirePassword -}}
This is not true

2024-02-07 16:55 UTC, netanelC commented on charts/serving/charts/pycsw-all/templates/deployment.yaml
> +{{- if and .Values.global.postgres.ssl.useExternal (not .Values.global.postgres.user.secretName) }}
This is ssl secret and not user secret

2024-02-07 16:55 UTC, netanelC commented on charts/shared/charts/heartbeat-manager/templates/configmap.yaml
> +  DB_SSL_REJECT_UNAUTHORIZED: {{ .Values.env.db.user.rejectUnauthorized | quote }}
Not true

2024-02-08 07:48 UTC, heliprokupetz14 commented on charts/ingestion/charts/ingestion-catalog/templates/secret.yaml
> +{{- if not .Values.global.postgres.ssl.useExternal -}}
fixed

2024-02-08 07:49 UTC, heliprokupetz14 commented on charts/ingestion/templates/configmap.yaml
> +  S3_DEST_SIG_VERSION: v{{ .Values.global.S3.destination.sigVersion }}
the source can be different from the destination.

2024-02-08 07:57 UTC, heliprokupetz14 commented on charts/serving/charts/nginx-s3-gateway/templates/configmap.yaml
> +  AWS_SIGS_VERSION: {{ .Values.global.S3.destination.sigVersion | quote }}
fixed

2024-02-08 07:58 UTC, heliprokupetz14 commented on values-dev.yaml
> +  # ====================================================================================================
removed

2024-02-08 07:59 UTC, heliprokupetz14 commented on values-dev.yaml
> +      secretName: 'catalog-3d-dev-secret'
keep this only in the user or also in the ssl?

2024-02-08 08:02 UTC, heliprokupetz14 commented on values-dev.yaml
> +
removed

2024-02-08 08:07 UTC, heliprokupetz14 commented on charts/serving/charts/pycsw-all/templates/deployment.yaml
> +{{- if and .Values.global.postgres.ssl.useExternal (not .Values.global.postgres.user.secretName) }}
fixed

2024-02-08 14:06 UTC, netanelC commented on values-dev.yaml
> +      secretName: 'catalog-3d-dev-secret'
See how it is in pycsw, make it the same

2024-02-08 15:30 UTC, netanelC requested changes
You didn't refer to my note:
"In some cases you wrote user instead of SSL, check again the PR and make the changes in the right places (I didn't comment all of them, be a good head)."

Handle this

2024-02-08 16:11 UTC, heliprokupetz14 commented on values-dev.yaml
> +      secretName: 'catalog-3d-dev-secret'
fixed

2024-02-08 16:12 UTC, heliprokupetz14 commented on values-dev.yaml
> +      requirePassword: true
added

2024-02-11 09:28 UTC, netanelC requested changes

2024-02-11 09:28 UTC, netanelC commented on charts/serving/charts/pycsw-all/templates/deployment.yaml
> +            {{- if .Values.global.postgres.requirePassword }}
Not true

2024-02-11 09:28 UTC, netanelC commented on charts/serving/charts/pycsw/templates/deployment.yaml
> +            {{- if .Values.global.postgres.requirePassword }}
Not true

2024-02-11 09:30 UTC, heliprokupetz14 commented on charts/serving/charts/pycsw-all/templates/deployment.yaml
> +            {{- if .Values.global.postgres.requirePassword }}
fixed

2024-02-11 09:31 UTC, heliprokupetz14 commented on charts/serving/charts/pycsw/templates/deployment.yaml
> +            {{- if .Values.global.postgres.requirePassword }}
fixed

2024-02-11 09:40 UTC, netanelC commented on charts/serving/charts/pycsw-all/templates/deployment.yaml
> +            {{- if .Values.global.postgres.requirePassword }}
Still not true

2024-02-11 09:40 UTC, netanelC commented on charts/serving/charts/pycsw/templates/deployment.yaml
> +            {{- if .Values.global.postgres.requirePassword }}
Still not true

2024-02-11 09:41 UTC, heliprokupetz14 commented on charts/serving/charts/pycsw-all/templates/deployment.yaml
> +            {{- if .Values.global.postgres.requirePassword }}
my mistake

2024-02-11 09:41 UTC, heliprokupetz14 commented on charts/serving/charts/pycsw/templates/deployment.yaml
> +            {{- if .Values.global.postgres.requirePassword }}
my mistake

2024-02-11 10:03 UTC, netanelC requested changes

2024-02-11 10:03 UTC, netanelC commented on values-dev.yaml
> -
Keep the empty line

2024-02-11 10:04 UTC, heliprokupetz14 commented on values-dev.yaml
> -
added

2024-02-11 10:05 UTC, heliprokupetz14 commented on charts/serving/charts/pycsw/templates/deployment.yaml
> +              - key: {{ .Values.authentication.ssl.certFileKey }}
fixed

2024-02-11 10:11 UTC, netanelC requested changes
Excellent! change also the stage and prod values :)

2024-02-11 10:24 UTC, netanelC requested changes

2024-02-11 10:24 UTC, netanelC commented on values-prod.yaml
> +    debug: true
Keep the debug false

2024-02-11 10:24 UTC, netanelC commented on values-stage.yaml
> +  environment: development
?

2024-02-11 10:24 UTC, netanelC commented on values-stage.yaml
> +    debug: true
Keep the debug false

2024-02-11 10:24 UTC, netanelC commented on values-stage.yaml
> -      url: http://common-job-manager-integration-service
Don't change it

2024-02-11 10:25 UTC, heliprokupetz14 commented on values-prod.yaml
> +    debug: true
fixed

2024-02-11 10:26 UTC, heliprokupetz14 commented on values-stage.yaml
> +  environment: development
oops

2024-02-11 10:26 UTC, heliprokupetz14 commented on values-stage.yaml
> +    debug: true
fixed

2024-02-11 10:37 UTC, netanelC requested changes

2024-02-11 10:37 UTC, netanelC commented on values-stage.yaml
> +      enabled: true
Why did you change it?

2024-02-11 10:41 UTC, netanelC approved these changes
Good job!
I don't accept "oops"!

2024-02-11 10:44 UTC, merged